### ISSUE TITLE
Duplicate tag "PartialLicense" in file partial.txt

### ISSUE THREAD

**Issue by aharte** [jbgutierrez/vim-partial#2]
When I generate helptags for vim-partial I get the message Duplicate tag "PartialLicense" in file partial.txt In that file, Items 3 and 9 are using the same tag. I think you meant for item 3 to be tagged as "PartialModes".

BTW, great plugin, I use this a lot. Thanks.

**Comment by jbgutierrez** [comment]
Yep, I meant that. Thanks!
